// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBa5tUZEOQmiuiTnqOypDHAANkpP4kdRc',
    appId: '1:260512256520:web:88e357995eb466c144f7bd',
    messagingSenderId: '260512256520',
    projectId: 'learnflutter-76911',
    authDomain: 'learnflutter-76911.firebaseapp.com',
    storageBucket: 'learnflutter-76911.firebasestorage.app',
    measurementId: 'G-Z7M77PYS8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FmdM3OpOFMTDp5f2cqSpZMYsbBRUOWg',
    appId: '1:260512256520:android:8a04af902b38f7b044f7bd',
    messagingSenderId: '260512256520',
    projectId: 'learnflutter-76911',
    storageBucket: 'learnflutter-76911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6-es4zCajsHaYn8T-iF46AX29j2Xqaw',
    appId: '1:260512256520:ios:110566b6e985d60b44f7bd',
    messagingSenderId: '260512256520',
    projectId: 'learnflutter-76911',
    storageBucket: 'learnflutter-76911.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6-es4zCajsHaYn8T-iF46AX29j2Xqaw',
    appId: '1:260512256520:ios:110566b6e985d60b44f7bd',
    messagingSenderId: '260512256520',
    projectId: 'learnflutter-76911',
    storageBucket: 'learnflutter-76911.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBa5tUZEOQmiuiTnqOypDHAANkpP4kdRc',
    appId: '1:260512256520:web:3ba11617ffa33d8b44f7bd',
    messagingSenderId: '260512256520',
    projectId: 'learnflutter-76911',
    authDomain: 'learnflutter-76911.firebaseapp.com',
    storageBucket: 'learnflutter-76911.firebasestorage.app',
    measurementId: 'G-6E5WZYD833',
  );
}
